coverage:
  precision: 2
  round: down
  range: "40...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 10%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "test/*"
  - "build/*"
  - "*/test/*"
  - "*/main.cpp"      

github_checks:
  annotations: true
  
